   let greetingStart = "Halo, ";
   let world = "dunia!";
   console.log(greetingStart + world);
   greetingStart = "Ciao, ";
   world = "mondo!";
   console.log(greetingStart + world);
   greetingStart = "Hola, ";
   world = "mundo!";
   console.log(greetingStart + world);
   greetingStart = "Привет, ";
   world = "мир!";
   console.log(greetingStart + world);
   greetingStart = "Ola, ";
   world = "mundo!";
   console.log(greetingStart + world);
   greetingStart = "Прывітанне, ";
   world = "Сусвет!";
   console.log(greetingStart + world);
   greetingStart = "Hei, ";
   world = "maailma!";
   console.log(greetingStart + world);
   greetingStart = "Witaj, ";
   world = "świecie!";
   console.log(greetingStart + world);
   greetingStart = "Γειά σου, ";
   world = "Κόσμε!";
   console.log(greetingStart + world);
   greetingStart = "Dia duit ar ";
   world = "domhan!";
   console.log(greetingStart + world);